theme: jekyll-theme-slate
title: Crypto for Friends: understanding a new paradigm
description: Introducción a la tecnología blockchain y DeFI - Prof. Marcos Vexina
url: "https://Crypto-for-Friends.github.io/"
layout: default
